name: Build multiplatform docker image

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "src/.vscode/**"
      - "src/.vs/**"
      - "README.*"
      - ".gitignore"
      - ".gitattributes"
  workflow_dispatch:

jobs:
  build-application:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      ### DEMO
      # This is an example of how you can use this action to build and push a multi-platform Docker image
      - name: Build Docker container and push it to GitHub Packages
        uses: lojoh/build-and-push-multi-platform-docker-images-action@2.0
        with:
          docker-args: |
            ReleaseVersion=${{ steps.version.outputs.version }}
          docker-context: .
          docker-file: src/DemoApp/Dockerfile
          docker-registry: ghcr.io/lojoh
          github-token: ${{ secrets.PAT }}
          image-name: multi-platform-demo-app
          tag: 1.2.3
          platform: linux/arm64,linux/amd64
      ### END OF DEMO
