name: Build multiplatform docker image

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "src/.vscode/**"
      - "src/.vs/**"
      - "README.*"
      - ".gitignore"
      - ".gitattributes"
  workflow_dispatch:

jobs:
  build-application:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      # Generate a semantic version number based on the latest tag
      # This is only here for demonstration purposes, you can skip this step.
      - uses: lojoh/lojoh-github-actions-private/.github/actions/generate-semantic-version-number@2.0
        id: version

      - name: Use version number
        run: echo ${{ steps.version.outputs.version }}

      ### DEMO
      # This is an example of how you can use this action to build and push a multi-platform Docker image
      - name: Build Docker container and push it to GitHub Packages
        uses: lojoh/build-and-push-multi-platform-docker-images-action@1.0
        with:
          docker-args: --build-arg GitHubPackagesAccessToken=${{ secrets.PAT }} --build-arg ReleaseVersion=${{ steps.version.outputs.version }}
          docker-context: .
          docker-file: src/DemoApp/Dockerfile
          docker-registry: ghcr.io/lojoh
          github-token: ${{ secrets.PAT }}
          image-name: multi-platform-demo-app
          tag: ${{ steps.version.outputs.version }}
          platform: linux/arm64,linux/amd64
      ### END OF DEMO

      # Create a git tag and push it if on the main branch
      # This is only here for demonstration purposes, you can skip this step.
      - name: Create git tag and push if on main branch
        uses: lojoh/lojoh-github-actions-private/.github/actions/git-tag-and-push@2.0
        if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request') && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          tag: ${{ steps.version.outputs.version }}
